name: check updates
on:
  schedule:
    - cron: "28 0 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.x"

      - id: generate
        uses: shogo82148/actions-github-app-token@v1

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate.outputs.token }}
          ref: main
          fetch-depth: 0
      - name: check updates
        run: |
          go run .
