name: check updates
on:
  schedule:
    - cron: "28 0 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.x"
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: check updates
        runs: |
          go run .
